encoding: utf-8

plugins:
  - jekyll-regex-replace

# SEO相关信息
title: 调查赚钱网
description: 分享互联网赚钱的技巧和项目，主打调查兼职赚钱项目，学生少妇带娃都可以实操，赚点买菜钱饭钱，提供最全的网上调查赚钱网站合集测评
keywords: 网上兼职,调查赚钱,付费调查赚钱,调研赚钱,做问卷赚钱
author: 调查赚钱网
footerText: 'Copyright © 网上赚钱兼职网'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://pingshanzhuangxiu.github.io'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://pingshanzhuangxiu.github.io

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 首页
    url: /
  - title: 网赚文章归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: false

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 显示访问量统计，由不蒜子提供服务
extCount: true

# 友情链接
links:
  - title: 调查赚钱网
    url: https://pingshanzhuangxiu.github.io

